# Add new source files here

SET(WORMUX_SRCS
main.cpp
character/body.cpp
character/body_list.cpp
character/character.cpp
character/clothe.cpp
character/member.cpp
character/move.cpp
character/movement.cpp
game/config.cpp
game/game.cpp
game/game_loop.cpp
game/game_mode.cpp
game/time.cpp
graphic/color.cpp
graphic/effects.cpp
graphic/font.cpp
graphic/fps.cpp
graphic/spriteanimation.cpp
graphic/spritecache.cpp
graphic/sprite.cpp
graphic/spriteframe.cpp
graphic/surface.cpp
graphic/text.cpp
graphic/text_list.cpp
graphic/video.cpp
gui/box.cpp
gui/button.cpp
gui/button_text.cpp
gui/check_box.cpp
gui/label.cpp
gui/list_box.cpp
gui/list_box_w_label.cpp
gui/msg_box.cpp
gui/null_widget.cpp
gui/picture_text_cbox.cpp
gui/picture_widget.cpp
gui/progress_bar.cpp
gui/question.cpp
gui/spin_button_big.cpp
gui/spin_button.cpp
gui/spin_button_picture.cpp
gui/text_box.cpp
gui/widget.cpp
gui/widget_list.cpp
include/action.cpp
include/action_handler.cpp
include/constant.cpp
interface/cursor.cpp
interface/game_msg.cpp
interface/interface.cpp
interface/keyboard.cpp
interface/loading_screen.cpp
interface/mouse.cpp
interface/weapon_menu.cpp
map/camera.cpp
map/ground.cpp
map/map.cpp
map/maps_list.cpp
map/sky.cpp
map/tile.cpp
map/tileitem.cpp
map/water.cpp
map/wind.cpp
menu/credits_menu.cpp
menu/game_menu.cpp
menu/main_menu.cpp
menu/menu.cpp
menu/network_connection_menu.cpp
menu/network_menu.cpp
menu/options_menu.cpp
menu/results_menu.cpp
network/chat.cpp
network/distant_cpu.cpp
network/network.cpp
network/randomsync.cpp
object/barrel.cpp
object/bonus_box.cpp
object/object_cfg.cpp
object/objects_list.cpp
object/physical_obj.cpp
object/physics.cpp
particles/body_member.cpp
particles/teleport_member.cpp
particles/bullet.cpp
particles/dark_smoke.cpp
particles/explosion_smoke.cpp
particles/fire.cpp
particles/ground_particles.cpp
particles/ill_bubble.cpp
particles/magic_star.cpp
particles/particle.cpp
particles/polecat_fart.cpp
particles/smoke.cpp
particles/star.cpp
sound/jukebox.cpp
team/results.cpp
team/team.cpp
team/team_energy.cpp
team/teams_list.cpp
tool/debug.cpp
tool/error.cpp
tool/euler_vector.cpp
tool/file_tools.cpp
tool/i18n.cpp
tool/math_tools.cpp
tool/random.cpp
tool/resource_manager.cpp
tool/stats.cpp
tool/string_tools.cpp
tool/xml_document.cpp
weapon/air_attack.cpp
weapon/airhammer.cpp
weapon/anvil.cpp
weapon/auto_bazooka.cpp
weapon/baseball.cpp
weapon/bazooka.cpp
weapon/blowtorch.cpp
weapon/bounce_ball.cpp
weapon/cluster_bomb.cpp
weapon/construct.cpp
weapon/crosshair.cpp
weapon/dynamite.cpp
weapon/explosion.cpp
weapon/gnu.cpp
weapon/grenade.cpp
weapon/gun.cpp
weapon/holly_grenade.cpp
weapon/jetpack.cpp
weapon/launcher.cpp
weapon/lowgrav.cpp
weapon/mine.cpp
weapon/ninja_rope.cpp
weapon/parachute.cpp
weapon/polecat.cpp
weapon/riot_bomb.cpp
weapon/shotgun.cpp
weapon/skip_turn.cpp
weapon/snipe_rifle.cpp
weapon/submachine_gun.cpp
weapon/suicide.cpp
weapon/supertux.cpp
weapon/syringe.cpp
weapon/teleportation.cpp
weapon/weapon_cfg.cpp
weapon/weapon.cpp
weapon/weapons_list.cpp
)
