.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH WORMUX 6 "april 08, 2006"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
wormux \- A game where funny characters launch funny weapons
.SH SYNOPSIS
.B wormux
.br
.SH DESCRIPTION
.PP
Wormux\fP is a free game where funny animals fight on a 2D map with
funny weapons. Though currently under heavy development, it is already 
very playable, with lots of weapons (Dynamite, Baseball Bat,
Teleportation, etc.). 
.PP
There are also lots of maps available for your battling pleasure!
Wormux takes the genre to the next level, with great customisation 
options leading to great gameplay. There is a wide selection of teams, 
from the Aliens to the Chickens. Also, new battlefields can be
downloaded from the Internet, making strategy an important part of
each battle.
.br
.SH SEE ALSO
.br
Have a look at http://wormux.org/
.br
.SH AUTHOR
Wormux was written by:
.br
- Jean-Christophe DUBERGA <jcduberga@gmx.de>
.br
- Laurent DEFERT SIMONNEAU <lodesi2@yahoo.fr>
.br
- Lawrence AZZOUG <lawrenceazzoug@wanadoo.fr>
.br 
- Matthieu FERTRE <matthieu.fertre@free.fr>
.br 
- Renaud LOTTIAUX <renaud.lottiaux@free.fr>
.br
- Victor STINNER <victor.stinner@haypocalc.com>
.PP
This manual page was written by Jean Parpaillon <artefact@altern.org>,
for the Debian project (but may be used by others).
