
SET(DATA_FILES
authors.dtd
authors.xml
body/beastieteam/arm.png
body/beastieteam/black.png
body/beastieteam/body.png
body/beastieteam/c1.png
body/beastieteam/c2.png
body/beastieteam/config.xml
body/beastieteam/dead.png
body/beastieteam/eyelid.png
body/beastieteam/eyes.png
body/beastieteam/foot.png
body/beastieteam/head.png
body/beastieteam/helmet.png
body/beastieteam/hoop.png
body/beastieteam/hula.png
body/beastieteam/jetpack-heli.png
body/beastieteam/jetpack.png
body/beastieteam/pupil.png
body/beastieteam/tail.png
body/beastieteam/yoyo.png
body/body.dtd
body/firefoxteam/arm1.png
body/firefoxteam/arm2.png
body/firefoxteam/black.png
body/firefoxteam/body.png
body/firefoxteam/c1.png
body/firefoxteam/c2.png
body/firefoxteam/config.xml
body/firefoxteam/dead.png
body/firefoxteam/ear-left.png
body/firefoxteam/ear-right.png
body/firefoxteam/eyelid.png
body/firefoxteam/eyes.png
body/firefoxteam/foot.png
body/firefoxteam/head.png
body/firefoxteam/helmet.png
body/firefoxteam/hoop.png
body/firefoxteam/hula.png
body/firefoxteam/jetpack-belt.png
body/firefoxteam/jetpack-fire.png
body/firefoxteam/jetpack.png
body/firefoxteam/pupil.png
body/firefoxteam/tail.png
body/firefoxteam/yoyo.png
body/gnuteam/arm.png
body/gnuteam/black.png
body/gnuteam/body.png
body/gnuteam/c1.png
body/gnuteam/c2.png
body/gnuteam/config.xml
body/gnuteam/dead.png
body/gnuteam/eyelid.png
body/gnuteam/eyes.png
body/gnuteam/foot.png
body/gnuteam/head.png
body/gnuteam/helmet.png
body/gnuteam/hoop.png
body/gnuteam/hula.png
body/gnuteam/jetpack-belt.png
body/gnuteam/jetpack-fire.png
body/gnuteam/jetpack.png
body/gnuteam/pupil.png
body/gnuteam/tail.png
body/gnuteam/yoyo.png
body/konqiteam/arm1.png
body/konqiteam/arm2.png
body/konqiteam/black.png
body/konqiteam/body.png
body/konqiteam/c1.png
body/konqiteam/c2.png
body/konqiteam/config.xml
body/konqiteam/dead.png
body/konqiteam/eyelid.png
body/konqiteam/eyes.png
body/konqiteam/foot-left.png
body/konqiteam/foot-right.png
body/konqiteam/helmet.png
body/konqiteam/hoop.png
body/konqiteam/horns.png
body/konqiteam/hula.png
body/konqiteam/nose.png
body/konqiteam/pupil.png
body/konqiteam/tail.png
body/konqiteam/wing.png
body/konqiteam/yoyo.png
body/nupikteam/arm.png
body/nupikteam/black.png
body/nupikteam/body.png
body/nupikteam/c1.png
body/nupikteam/c2.png
body/nupikteam/config.xml
body/nupikteam/dead.png
body/nupikteam/eyelid.png
body/nupikteam/eyes.png
body/nupikteam/fixedarm.png
body/nupikteam/foot.png
body/nupikteam/head.png
body/nupikteam/helmet.png
body/nupikteam/hoop.png
body/nupikteam/hula.png
body/nupikteam/jetpack-heli.png
body/nupikteam/jetpack.png
body/nupikteam/pupil.png
body/nupikteam/spines1.png
body/nupikteam/spines2.png
body/nupikteam/yoyo.png
body/oooteam/black.png
body/oooteam/body.png
body/oooteam/c1.png
body/oooteam/c2.png
body/oooteam/config.xml
body/oooteam/dead.png
body/oooteam/eyelid.png
body/oooteam/eyes.png
body/oooteam/foot.png
body/oooteam/helmet.png
body/oooteam/hoop.png
body/oooteam/hula.png
body/oooteam/nozzle.png
body/oooteam/pupil.png
body/oooteam/wingleft.png
body/oooteam/wingright.png
body/oooteam/yoyo.png
body/phpteam/arm.png
body/phpteam/black.png
body/phpteam/body.png
body/phpteam/c1.png
body/phpteam/c2.png
body/phpteam/config.xml
body/phpteam/dead.png
body/phpteam/ear-left.png
body/phpteam/ear-right.png
body/phpteam/eyelid.png
body/phpteam/eyes.png
body/phpteam/foot-left.png
body/phpteam/foot-right.png
body/phpteam/helmet.png
body/phpteam/hoop.png
body/phpteam/hula.png
body/phpteam/jetpack-belt.png
body/phpteam/jetpack-fire.png
body/phpteam/jetpack.png
body/phpteam/nose.png
body/phpteam/pupil.png
body/phpteam/tail.png
body/phpteam/yoyo.png
body/snortteam/arm.png
body/snortteam/black.png
body/snortteam/body.png
body/snortteam/c1.png
body/snortteam/c2.png
body/snortteam/config.xml
body/snortteam/dead.png
body/snortteam/eyelid.png
body/snortteam/eyes.png
body/snortteam/head.png
body/snortteam/helmet.png
body/snortteam/hoop.png
body/snortteam/hula.png
body/snortteam/jetpack-belt.png
body/snortteam/jetpack-fire.png
body/snortteam/jetpack.png
body/snortteam/pupil.png
body/snortteam/tail.png
body/snortteam/yoyo.png
body/spipteam/arm.png
body/spipteam/black.png
body/spipteam/body.png
body/spipteam/c1.png
body/spipteam/c2.png
body/spipteam/config.xml
body/spipteam/dead.png
body/spipteam/eyelid.png
body/spipteam/eyes.png
body/spipteam/foot.png
body/spipteam/head.png
body/spipteam/helmet.png
body/spipteam/hoop.png
body/spipteam/hula.png
body/spipteam/jetpack-belt.png
body/spipteam/jetpack-fire.png
body/spipteam/jetpack.png
body/spipteam/pupil.png
body/spipteam/tail.png
body/spipteam/yoyo.png
body/thunderbirdteam/black.png
body/thunderbirdteam/body.png
body/thunderbirdteam/c1.png
body/thunderbirdteam/c2.png
body/thunderbirdteam/config.xml
body/thunderbirdteam/dead.png
body/thunderbirdteam/eyelid.png
body/thunderbirdteam/eyes.png
body/thunderbirdteam/foot.png
body/thunderbirdteam/hair.png
body/thunderbirdteam/helmet.png
body/thunderbirdteam/hoop.png
body/thunderbirdteam/hula.png
body/thunderbirdteam/nozzle.png
body/thunderbirdteam/pupil.png
body/thunderbirdteam/wingleft.png
body/thunderbirdteam/wingright.png
body/thunderbirdteam/yoyo.png
body/tuxteam/black.png
body/tuxteam/body.png
body/tuxteam/c1.png
body/tuxteam/c2.png
body/tuxteam/config.xml
body/tuxteam/dead.png
body/tuxteam/eyelid.png
body/tuxteam/eyes.png
body/tuxteam/foot.png
body/tuxteam/helmet.png
body/tuxteam/hoop.png
body/tuxteam/hula.png
body/tuxteam/nozzle.png
body/tuxteam/pupil.png
body/tuxteam/wing.png
body/tuxteam/yoyo.png
body/wilberteam/arm.png
body/wilberteam/black.png
body/wilberteam/body.png
body/wilberteam/c1.png
body/wilberteam/c2.png
body/wilberteam/config.xml
body/wilberteam/dead.png
body/wilberteam/eyelid.png
body/wilberteam/eyes.png
body/wilberteam/foot.png
body/wilberteam/head.png
body/wilberteam/helmet.png
body/wilberteam/hoop.png
body/wilberteam/hula.png
body/wilberteam/jetpack-belt.png
body/wilberteam/jetpack-fire.png
body/wilberteam/jetpack.png
body/wilberteam/pupil.png
body/wilberteam/yoyo.png
body/workraveteam/arm.png
body/workraveteam/black.png
body/workraveteam/body.png
body/workraveteam/c1.png
body/workraveteam/c2.png
body/workraveteam/config.xml
body/workraveteam/dead.png
body/workraveteam/eyelid.png
body/workraveteam/eyes.png
body/workraveteam/foot.png
body/workraveteam/head.png
body/workraveteam/helmet.png
body/workraveteam/hoop.png
body/workraveteam/hula.png
body/workraveteam/jetpack-belt.png
body/workraveteam/jetpack-fire.png
body/workraveteam/jetpack.png
body/workraveteam/pupil.png
body/workraveteam/yoyo.png
cursors.xml
font/DejaVuSans.ttf
game_mode/classic_objects.xml
game_mode/classic.xml
game_mode/game_mode.dtd
game_mode/objects.dtd
gfx/arrow.png
gfx/pointer.png
gfx/water_bottom.png
gfx/water.png
graphism.dtd
graphism.xml
interface/background_interface.png
interface/clock_background.png
interface/clock.png
interface/cross.png
interface/cursors/arrow-down.left.png
interface/cursors/arrow-down.png
interface/cursors/arrow-down.right.png
interface/cursors/arrow-left.png
interface/cursors/arrow-right.png
interface/cursors/arrow-top.left.png
interface/cursors/arrow-top.png
interface/cursors/arrow-top.right.png
interface/cursors/hand-cursor.png
interface/cursors/hand-fire.left.png
interface/cursors/hand-fire.png
interface/cursors/hand-fire.right.png
interface/cursors/hand-move.png
interface/pause.png
interface/quit.png
interface/small_background_interface.png
interface/wind_indicator.png
interface/wind.png
map/aquarium/background.png
map/aquarium/config.xml
map/aquarium/preview.jpg
map/aquarium/sky.jpg
map/arbre/arbre.png
map/arbre/config.xml
map/arbre/fond.jpg
map/arbre/gland-anim.png
map/arbre/preview.jpg
map/bankiz/bankiz.png
map/bankiz/config.xml
map/bankiz/flocon.png
map/bankiz/preview.jpg
map/bankiz/sky.jpg
map/banquise/background.jpg
map/banquise/banquise.png
map/banquise/config.xml
map/banquise/flocon.png
map/banquise/preview.jpg
map/battlenight/battlenight-all.jpg
map/battlenight/battlenight-bg.jpg
map/battlenight/battlenight-fg.png
map/battlenight/config.xml
map/catacombes/background1.png
map/catacombes/config.xml
map/catacombes/preview.jpg
map/catacombes/sky1.jpg
map/champignon/background.png
map/champignon/config.xml
map/champignon/preview.jpg
map/champignon/sky.jpg
map/cheese/config.xml
map/cheese/emmental.png
map/cheese/minicheese.png
map/cheese/preview.jpg
map/cheese/sky.jpg
map/christmas/config.xml
map/christmas/flocon.png
map/christmas/map.png
map/christmas/preview.jpg
map/christmas/sky.jpg
map/cowland/config.xml
map/cowland/map.png
map/cowland/nuage.png
map/cowland/preview.jpg
map/cowland/sky.jpg
map/crystal/config.xml
map/crystal/crystal.png
map/crystal/preview.jpg
map/crystal/sky.jpg
map/desert/config.xml
map/desert/desert_bg.jpg
map/desert/desert.png
map/desert/desert_preview.jpg
map/easterisland/config.xml
map/easterisland/map.png
map/easterisland/preview.jpg
map/easterisland/sky.jpg
map/easterisland/wp.png
map/electronik/background.png
map/electronik/config.xml
map/electronik/preview.jpg
map/electronik/sky.jpg
map/funkyIsland/clouds.png
map/funkyIsland/config.xml
map/funkyIsland/island_bg.jpg
map/funkyIsland/island.png
map/funkyIsland/preview.jpg
map/goodandevil/config.xml
map/goodandevil/goodandevil.png
map/goodandevil/preview.jpg
map/goodandevil/sky.jpg
map/greehills/config.xml
map/greehills/greenhills.png
map/greehills/greenhills_sky.jpg
map/greehills/preview.jpg
map/greehills/star.png
map/grenouilles/config.xml
map/grenouilles/grenouilles.png
map/grenouilles/jungle.jpg
map/grenouilles/nuage.png
map/grenouilles/preview.jpg
map/halloween/config.xml
map/halloween/map.png
map/halloween/preview.jpg
map/halloween/sky.jpg
map/halloween/wp.png
map/hell/bones.png
map/hell/config.xml
map/hell/hell.png
map/hell/hellsky.jpg
map/hell/preview.jpg
map/hive/BG.jpg
map/hive/config.xml
map/hive/FG.png
map/hive/part_effect_strip.png
map/hive/preview.jpg
map/island/config.xml
map/island/island.png
map/island/preview.jpg
map/island/sky.jpg
map/leafs/back.jpg
map/leafs/birds.png
map/leafs/config.xml
map/leafs/front.png
map/leafs/preview.jpg
map/map.dtd
map/monkeybubbleworld/config.xml
map/monkeybubbleworld/feuille.png
map/monkeybubbleworld/monkeybubbleworld.png
map/monkeybubbleworld/preview.jpg
map/monkeybubbleworld/sky.jpg
map/moon-4m/config.xml
map/moon-4m/map.png
map/moon-4m/preview.jpg
map/moon-4m/sky.jpg
map/paradis/config.xml
map/paradis/decor_paradis_BG.jpg
map/paradis/decor_paradis.png
map/paradis/paradis_preview.jpg
map/pillars/BG.jpg
map/pillars/config.xml
map/pillars/FG.png
map/pillars/preview.jpg
map/pirates/config.xml
map/pirates/islands.jpg
map/pirates/pirates.png
map/pirates/preview.jpg
map/prehistorik/config.xml
map/prehistorik/fond.jpg
map/prehistorik/prehistorik.png
map/prehistorik/preview.jpg
map/pumpkins/config.xml
map/pumpkins/dessin_fond.png
map/pumpkins/feuille.png
map/pumpkins/map.png
map/pumpkins/preview.jpg
map/qingqong/config.xml
map/qingqong/preview.jpg
map/qingqong/qingqong.png
map/qingqong/sky.jpg
map/randomamoebas/config.xml
map/randomamoebas/preview.jpg
map/randomamoebas/sky.jpg
map/randomamoebas/texture.png
map/random/config.xml
map/random/palm-tree.png
map/random/preview.jpg
map/random/sky.jpg
map/random/texture.png
map/random/tresor1.png
map/random/tresor2.png
map/space2/config.xml
map/space2/map.png
map/space2/preview.jpg
map/space2/sky.jpg
map/tic-tac-toe/BG.jpg
map/tic-tac-toe/config.xml
map/tic-tac-toe/FG.png
map/tic-tac-toe/part_effect_strip.png
map/tic-tac-toe/preview.jpg
map/towers/config.xml
map/towers/map.png
map/towers/preview.jpg
map/towers/sky.jpg
map/vulcano/background.png
map/vulcano/config.xml
map/vulcano/preview.jpg
map/vulcano/sky2.jpg
map/wildwestdv/config.xml
map/wildwestdv/map.png
map/wildwestdv/preview.jpg
map/wildwestdv/sky.jpg
menu/annulus_background.png
menu/annulus_foreground.png
menu/audio_label.png
menu/background_credits.png
menu/background_network.png
menu/background_options.png
menu/background_play.png
menu/background.png
menu/big_left.png
menu/big_right.png
menu/button.png
menu/cancel.png
menu/check.png
menu/config_label.png
menu/disabled_back.png
menu/disabled_front.png
menu/display_energy.png
menu/display_name.png
menu/display_wind_particles.png
menu/down.png
menu/enabled.png
menu/fps.png
menu/fullscreen.png
menu/ico_maps.png
menu/ico_skins.png
menu/ico_sounds.png
menu/ico_weapons.png
menu/left.png
menu/loading.png
menu/map_label.png
menu/minus.png
menu/mode_label.png
menu/music_enable.png
menu/plus.png
menu/podium.png
menu/resolution.png
menu/right.png
menu/scroll_on_border.png
menu/send_txt.png
menu/sound_effects_enable.png
menu/sound_frequency.png
menu/team_number.png
menu/teams_label.png
menu/timing_end_turn.png
menu/timing_turn.png
menu/up.png
menu/validate.png
menu/video_label.png
music/ingame/fear.m3u
music/ingame/funfair.m3u
music/ingame/ingame.m3u
music/ingame/Mike_Errecart.-.Monkey-bubble.ogg
music/ingame/monkey.m3u
music/ingame/Olivier_Militon.-.Apnee2.ogg
music/ingame/Olivier_Militon.-.Apnee.ogg
music/ingame/Olivier_Militon.-.Etrange_epouvantable.ogg
music/ingame/Olivier_Militon.-.Like_a_rock.ogg
music/ingame/Olivier_Militon.-.Vers_solitaire.ogg
music/ingame/Olivier_Militon.-.Vogue_a_lame.ogg
music/ingame/sea.m3u
music/menu/menu.m3u
music/menu/Olivier_Militon.-.Le_Calumet_F.ogg
music/menu/Olivier_Militon.-.Le_Calumet.ogg
music/profile.xml
object/barrel.png
object/blue_star.png
object/bonus_box.png
object/dark_smoke.png
object/fire.png
object/ill_bubble.png
object/medkit.png
object/pink_star.png
object/smoke2.png
object/smoke3.png
object/smoke.png
object/star.png
object/yellow_star.png
sound/default/crazy_01.ogg
sound/default/crazy_02.ogg
sound/default/crazy_03.ogg
sound/default/crazy_04.ogg
sound/default/crazy_05.ogg
sound/default/cuss_01.ogg
sound/default/cuss_02.ogg
sound/default/cuss_03.ogg
sound/default/cuss_04.ogg
sound/default/death_01.ogg
sound/default/death_02.ogg
sound/default/fire_01.ogg
sound/default/fire_02.ogg
sound/default/hehe.ogg
sound/default/hop_01.ogg
sound/default/out_01.ogg
sound/default/profile.xml
sound/default/sink.ogg
sound/default/skip_turn.ogg
sound/default/step.ogg
sound/default/suicide_01.ogg
sound/default/superjump_01.ogg
sound/default/uuh_01.ogg
sound/default/uuh_02.ogg
sound/default/uuh_03.ogg
sound/default/uuh_04.ogg
sound/default/uuh_05.ogg
sound/default/uuh_06.ogg
sound/default/uuh_07.ogg
sound/default/uuh_08.ogg
sound/flying/flying.ogg
sound/flying/profile.xml
sound/francais/crazy.ogg
sound/francais/fire_01.ogg
sound/francais/fire_02.ogg
sound/francais/profile.xml
sound/share/character_change.ogg
sound/share/end_turn.ogg
sound/share/explosion.ogg
sound/share/frog_music.ogg
sound/share/laughing.ogg
sound/share/menu/cancel.ogg
sound/share/menu/clic.ogg
sound/share/menu/error.ogg
sound/share/menu/ok.ogg
sound/share/menu/weapon_menu_toggled.ogg
sound/share/profile.xml
sound/share/step.ogg
sound/share/victory.ogg
sound/share/weapon/aircraft_bomb_falling.ogg
sound/share/weapon/aircraft_flying.ogg
sound/share/weapon/airhammer_selected.ogg
sound/share/weapon/airhammer_used.ogg
sound/share/weapon/alleluia.ogg
sound/share/weapon/anvil_collision.ogg
sound/share/weapon/anvil_fall.ogg
sound/share/weapon/baseball.ogg
sound/share/weapon/commit_suicide.ogg
sound/share/weapon/disco_grenade_music.ogg
sound/share/weapon/dynamite_exp.ogg
sound/share/weapon/dynamite_fuze.ogg
sound/share/weapon/dynamite.ogg
sound/share/weapon/flame.ogg
sound/share/weapon/gnu_bounce.ogg
sound/share/weapon/grenade_bounce.ogg
sound/share/weapon/gun.ogg
sound/share/weapon/holly_grenade_bounce.ogg
sound/share/weapon/jetpack.ogg
sound/share/weapon/load.ogg
sound/share/weapon/m16.ogg
sound/share/weapon/mine_beep.ogg
sound/share/weapon/pistolet.ogg
sound/share/weapon/ricoche1.ogg
sound/share/weapon/ricoche2.ogg
sound/share/weapon/ricoche3.ogg
sound/share/weapon/riot_bomb_exp.ogg
sound/share/weapon/shotgun.ogg
sound/share/weapon/supertux_flying.ogg
sound/share/weapon/teleport_land.ogg
sound/share/weapon/teleport_start.ogg
team/beastieteam/dead.png
team/beastieteam/flag64.png
team/beastieteam/flag.png
team/beastieteam/team.xml
team/firefoxteam/dead.png
team/firefoxteam/flag64.png
team/firefoxteam/flag.png
team/firefoxteam/team.xml
team/gnuteam/dead.png
team/gnuteam/flag64.png
team/gnuteam/flag.png
team/gnuteam/team.xml
team/konqiteam/dead.png
team/konqiteam/flag64.png
team/konqiteam/flag.png
team/konqiteam/team.xml
team/nupikteam/dead.png
team/nupikteam/flag64.png
team/nupikteam/flag.png
team/nupikteam/team.xml
team/oooteam/dead.png
team/oooteam/flag64.png
team/oooteam/flag.png
team/oooteam/team.xml
team/phpteam/dead.png
team/phpteam/flag64.png
team/phpteam/flag.png
team/phpteam/team.xml
team/snortteam/dead.png
team/snortteam/flag64.png
team/snortteam/flag.png
team/snortteam/team.xml
team/spipteam/dead.png
team/spipteam/flag64.png
team/spipteam/flag.png
team/spipteam/flag.svg
team/spipteam/team.xml
team/team.dtd
team/thunderbirdteam/dead.png
team/thunderbirdteam/flag64.png
team/thunderbirdteam/flag.png
team/thunderbirdteam/team.xml
team/tuxteam/dead.png
team/tuxteam/flag64.png
team/tuxteam/flag.png
team/tuxteam/team.xml
team/wilberteam/dead.png
team/wilberteam/flag64.png
team/wilberteam/flag.png
team/wilberteam/team.xml
team/workraveteam/dead.png
team/workraveteam/flag64.png
team/workraveteam/flag.png
team/workraveteam/team.xml
uninstall.xpm
weapon/air_attack/air_attack_ico.png
weapon/air_attack/air_attack_plane.png
weapon/air_attack/air_attack.png
weapon/air_attack/obus.png
weapon/airhammer/airhammer_ico.png
weapon/airhammer/airhammer_impact.png
weapon/airhammer/airhammer.png
weapon/anvil/anvil_ico.png
weapon/anvil/anvil_launcher.png
weapon/anvil/anvil.png
weapon/baseball/baseball_hit.png
weapon/baseball/baseball_ico.png
weapon/baseball/baseball.png
weapon/bazooka/baz_cible.png
weapon/bazooka/bazooka_auto_ico.png
weapon/bazooka/bazooka_ico.png
weapon/bazooka/brown_bazooka.png
weapon/bazooka/green_bazooka.png
weapon/bazooka/missile.png
weapon/bazooka/yellow_bazooka.png
weapon/blowtorch/blowtorch_ico.png
weapon/blowtorch/blowtorch.png
weapon/blowtorch/fire.png
weapon/bounce_ball/bounce_ball_ico.png
weapon/bounce_ball/bounce_ball.png
weapon/cluster_bomb/clusterbomb_ico.png
weapon/cluster_bomb/clusterbomb.png
weapon/cluster_bomb/cluster.png
weapon/construct/construct_icon_mini.png
weapon/construct/construct_icon.png
weapon/construct/construct_spr.png
weapon/disco_grenade/disco_grenade_ico.png
weapon/disco_grenade/disco_grenade.png
weapon/dynamite/dynamite_ani.png
weapon/dynamite/dynamite_ico.png
weapon/dynamite/dynamite.png
weapon/flamethrower/flame_bullet.png
weapon/flamethrower/flame_ico.png
weapon/flamethrower/flame.png
weapon/gnu/gnu_ico.png
weapon/gnu/gnulauncher.png
weapon/gnu/gnu.png
weapon/grapple/grapple_hook.png
weapon/grapple/grapple_ico.png
weapon/grapple/grapple_node.png
weapon/grapple/grapple.png
weapon/grenade/grenade_ico.png
weapon/grenade/grenade.png
weapon/gun/gun_bullet.png
weapon/gun/gun_fire.png
weapon/gun/gun_ico.png
weapon/gun/gun.png
weapon/jet_pack/jet_pack_ico.png
weapon/lowgrav/lowgrav_ico.png
weapon/m16/m16_ico.png
weapon/m16/m16.png
weapon/mine/mine_anim.png
weapon/mine/mine_ico.png
weapon/mine/mine_impact.png
weapon/mine/mine.png
weapon/parachute/parachute_ico.png
weapon/parachute/parachute.png
weapon/polecat/polecat_fart.png
weapon/polecat/polecat_ico.png
weapon/polecat/polecatlauncher.png
weapon/polecat/polecat.png
weapon/riot_bomb/missile.png
weapon/riot_bomb/riot_ico.png
weapons.dtd
weapon/shotgun/buckshot.png
weapon/shotgun/shotgun_ico.png
weapon/shotgun/shotgun.png
weapon/skip_turn/skipturn_ico.png
weapon/skip_turn/skipturn.png
weapon/snipe_rifle/gun_fire.png
weapon/snipe_rifle/snipe_rifle_ico.png
weapon/snipe_rifle/snipe_rifle_laser.png
weapon/snipe_rifle/snipe_rifle.png
weapon/suicide/suicide_ico.png
weapon/suicide/suicide.png
weapon/supertux/superman.png
weapon/supertux/supertux_ico.png
weapon/supertux/supertux.png
weapons.xml
weapon/syringe/syringe_ico.png
weapon/syringe/syringe.png
weapon/teleportation/teleportation_ico.png
weapon/teleportation/teleportation.png
wormux_128x128.png
wormux_128x128.xpm
wormux_256x256.png
wormux_32x32.png
wormux_32x32.xpm
wormux_default_config.xml
wormux.desktop
wormux.svg
)
