#! /bin/sh

echo "[+] Clean files generated by autoconf, aclocal, automake and configure"
rm -f config.log config.status mkinstalldirs configure aclocal.m4
rm -rf autom4te.cache src/.deps
find . -name Makefile.am | sed 's|\(.*\).am$|\1.in \1|g' | xargs rm -f
