/******************************************************************************
 *  Wormux is a convivial mass murder game.
 *  Copyright (C) 2001-2010 Wormux Team.
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA
 ******************************************************************************/

#ifndef WMX_LOG
#warning this file must not be included!
#endif

/*
 * WARNING: this file is autogenerated, do not edit it by hand!
 *
 */

std::string used_debug_masks = "action_handler | action_handler.menu | action_time | ai | ai.move | ai.shoot | body | body_anim | body.clothe | body.movement | body.state | bonus | box | camera.shake | character | character.collision | character.energy | damage | explosion | eye | game | game.endofturn | game_mode | game.statechange | ghost | grapple.hook | grapple.node | ground_generator.element | ground_generator.island | jukebox | jukebox.play | lst_objects | map | map.generation | map.load | map.random | menu | mine | mouse | network | network.game_master | network.refresh_games_list | network.state | network.thread | network.traffic | network.turn_master | physical | physical.mem | physic.compute | physic.move | physic.overlapping | physic.physic | physic.position | physic.state | random | random.get | singleton | sprite | team | test_rectangle | time.increase | time.skip | time.waiting | weapon | weapon.change | weapon.gnu | weapon.handposition | weapon.polecat | weapon.projectile | weapon.shoot | widget.border | widgetlist | wind | xml | xml.entities | xml.tree";
